module.exports.Token = require('./token.model')
module.exports.User = require('./user.model')
module.exports.Post = require('./post.model')
module.exports.Comment = require('./comment.model')
module.exports.UserData = require('./user-data.model')
