// register
POST {{base}}/auth/register
Content-Type: application/json

{
    "name": "dani",
    "email": "dani@gmail.com",
    "password": "test123456"
}

###

// login
POST {{base}}/auth/login
Content-Type: application/json

{
    "email": "dani@gmail.com",
    "password": "test123456"
}

###

// logout
POST {{base}}/auth/logout
Content-Type: application/json

{
    "refreshToken": ""
}

###

// refresh token
POST {{base}}/auth/refresh-tokens
Content-Type: application/json

{
    "refreshToken": ""
}

###
// reset password
POST {{base}}/auth/reset-password/?token=
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "password": "test1234567"
}
